// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.
 

import type { Database as DB, Json as DBJson } from "./database.types";

export type Database = DB;
export type Json = DBJson;

export type Tables<T extends keyof DB["public"]["Tables"]> =
  DB["public"]["Tables"][T]["Row"];
export type Enums<T extends keyof DB["public"]["Enums"]> =
  DB["public"]["Enums"][T];

// Project reference: vxghhiswchuhhdivwzyk
// Last updated: 2025-10-26T20:14:26.105496
