// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.
/* eslint-disable @typescript-eslint/no-empty-object-type */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      players: {
        Row: {
          id: string
          user_id: string
          username: string
          firstname: string
          lastname: string
          dob: string | null
          gender: string | null
          email: string
          phone: string | null
          casino: string | null
          vip_level: number
          total_deposits: number
          last_email_sent: string | null
          preferences: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          username: string
          firstname: string
          lastname: string
          dob?: string | null
          gender?: string | null
          email: string
          phone?: string | null
          casino?: string | null
          vip_level?: number
          total_deposits?: number
          last_email_sent?: string | null
          preferences?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          username?: string
          firstname?: string
          lastname?: string
          dob?: string | null
          gender?: string | null
          email?: string
          phone?: string | null
          casino?: string | null
          vip_level?: number
          total_deposits?: number
          last_email_sent?: string | null
          preferences?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      tasks: {
        Row: {
          id: string
          player_id: string | null
          title: string
          description: string | null
          priority: string
          status: string
          due_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          player_id?: string | null
          title: string
          description?: string | null
          priority?: string
          status?: string
          due_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          player_id?: string | null
          title?: string
          description?: string | null
          priority?: string
          status?: string
          due_date?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
    CompositeTypes: {}
  }
}

// Project reference: ccd972dd-2033-400a-bfb4-4562f0419650
